name: quick_flashcards
description: A cross-platform (Android, iOS) mobile application developed for creating flashcards as quick as possible.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  swipe_cards: ^2.0.0+1
  flutter_card_swiper: ^5.1.0
  flip_card: ^0.7.0
  firebase_core: ^2.14.0
  flutter_riverpod: ^2.3.6
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  flutter_spinkit: ^5.2.0
  another_flushbar: ^1.12.30
  mockito: ^5.4.2
  build_runner: ^2.4.6
  firebase_core_platform_interface: ^4.8.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  tabler_icons: ^2.5.0+1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 200
